#+TITLE: biobuntu connections
#+Author: Thomas Alexander Gerds
#+setupfile:~/emacs-genome/snps/org-templates/setup-biobuntu.org
#+superman-export-target: html

* Preparation

In all of the following =*Terminal*= codes you should replace =bio737=
with your own *KU-id*. Shout out loud (we need to be able to hear you
in bygning 15) if you run into unclearness, typos or really unsolvable
problems ...

** Biostat computing servers 
The computing servers with ssh access are 

- =doob= (virtual)
- =rasch= (virtual)
- =rao= (linux, cue system)
- =cox= (linux, cue system)  
# - =gauss= (48 cores, anarchy)
# - =borel= (48 cores, anarchy)
# - =bayes= (64 cores, cue system)
# - =fisher= (64 cores, cue system)

To connect with one of these machines you need to either be connected
via cable at CSS or open a vpn connection (see instructions below).
Then, you can login to =doob= via:

#+BEGIN_SRC sh
ssh -X bio737@doob
#+END_SRC

*** Hard to remember?

Add aliases to the file =~/.bashrc=

#+BEGIN_SRC sh
alias cox='ssh -X bio737@cox'
alias rao='ssh -X bio737@rao'
alias doob='ssh -X bio737@doob'
alias rasch='ssh -X bio737@rasch'
#+END_SRC

* Eduroam

** networkmanager

You are on your own, but this should work:

Wi-fi Security

Security: WPA & WPA2 Enterprise
Authentication: Protected EAP (PEAP)
No CA certificate is required
PEAP version: Version 0
Inner authentication: MSCHAPv2
Username: bio737
Password: xxxx

* Open vpn from a wireless connection 

Install cisco anyconnect and consider instructions inside
KU intranet:

- vpn.sund.ku.dk
- library.sund.ku.dk 

To open the vpn connection you need apply two-factor authentication.
You can use a Yubikey or install NetIQ Advanced Authentication on your
phone/tablet.

** Graphical user interface

#+BEGIN_SRC sh
/opt/cisco/anyconnect/bin/vpnui
#+END_SRC   
  
** Command line
   
#+BEGIN_SRC sh
/opt/cisco/anyconnect/bin/vpn -s connect "KU VPN"
# lazy?
printf 'bio737\nXXXXX\ny' |   /opt/cisco/anyconnect/bin/vpn -s connect "KU VPN"
#+END_SRC




